# Generated by Django 5.0.6 on 2024-07-04 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_post", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="post",
            table=None,
        ),
    ]
